### ISSUE TITLE
Will you try to compile the windows version? 

### ISSUE THREAD

**Issue by edenlin** [stephenc222/mysql_vss#2]
The os I am learning is windows,
I'm trying to figure out how to install this plugin in windows...Q_Q

**Comment by stephenc222** [comment]
@edenlin I'm happy to look at supporting Windows. I can't give an exact timeline however when/if I add Windows support.

**Comment by edenlin** [comment]
May I ask you a question again？
What are your MySQL Server hardware specifications in Linux? 
If it is convenient for you.........😳

**Comment by stephenc222** [comment]
mysql_vss will run with any MySQL server running version 8 of MySQL, assuming this extension was correctly compiled. Closing.

**Comment by edenlin** [comment]
Thank you for your reply 👍
